# SPDX-FileCopyrightText: 2026 Povl Filip Sonne-Frederiksen
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Embed apps/ruxd/migrations/NNN_<name>.sql into a C++ source, so the ruxd
# binary carries its own schema (no migrations directory to install or find).
#
# Run as a script:  cmake -DMIGRATIONS_DIR=<dir> -DOUTPUT=<file.cpp> -P <this>
# The generated file defines ruxd::pg::embedded_migrations() (declared in
# include/pg/migrations.hpp), sorted by version.

file(GLOB _files "${MIGRATIONS_DIR}/*.sql")
list(SORT _files)

set(_body "")
foreach(_file IN LISTS _files)
  get_filename_component(_name "${_file}" NAME_WE)
  if(NOT _name MATCHES "^([0-9]+)_(.+)$")
    message(FATAL_ERROR "migration ${_file}: name it NNN_<name>.sql")
  endif()
  set(_version "${CMAKE_MATCH_1}")
  math(EXPR _version "${_version}") # strip leading zeros
  set(_label "${CMAKE_MATCH_2}")
  file(READ "${_file}" _sql)
  string(FIND "${_sql}" ")ruxdsql\"" _clash)
  if(NOT _clash EQUAL -1)
    message(FATAL_ERROR "migration ${_file} contains the raw-string delimiter")
  endif()
  string(APPEND _body
    "      {${_version}, \"${_label}\", R\"ruxdsql(${_sql})ruxdsql\"},\n")
endforeach()

set(_content "// Generated by apps/ruxd/cmake/EmbedMigrations.cmake. Do not edit.
// NOLINTBEGIN
#include \"pg/migrations.hpp\"

namespace ruxd::pg {

const std::vector<Migration> &embedded_migrations() {
  static const std::vector<Migration> migrations{
${_body}  };
  return migrations;
}

} // namespace ruxd::pg
// NOLINTEND
")

# Only touch the file when it changes, so an unchanged schema rebuilds nothing.
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _old)
  if(_old STREQUAL _content)
    return()
  endif()
endif()
file(WRITE "${OUTPUT}" "${_content}")
