# SPDX-FileCopyrightText: 2025 Povl Filip Sonne-Frederiksen
# SPDX-License-Identifier: GPL-3.0-or-later

# Fish shell completions for rux CLI
# Generated by scripts/generate_fish_completions.py

# Disable default file completions
complete -c rux -f

# Global options (available at all levels)
complete -c rux -s h -l help -d "Print this help message and exit"
complete -c rux -s v -l verbose -d "Increase verbosity, use -vv & -vvv for more details." -r
complete -c rux -s V -l version -d "Show version information"
complete -c rux -s L -l license -d "Show license information"
complete -c rux -s D -l visualize -d "Enable visualization of processing steps"
complete -c rux -s p -l project -r

# top-level subcommands
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "assemble" -d "Assemble multiple scans into one database"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "create" -d "Create derived data from project"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "import" -d "Import data from external sources"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "export" -d "Export data to external formats"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "get" -d "Get data from project database"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "set" -d "Set data in project database"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "del" -d "Delete data from project database"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "info" -d "Display project database summary"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "log" -d "Display pipeline execution history"
complete -c rux -n "not __fish_seen_subcommand_from assemble create import export get set del info log view" -a "view" -d "Visualize point clouds and meshes"

# Options for: assemble
complete -c rux -n "__fish_seen_subcommand_from assemble" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from assemble" -s o -l out -r

# create subcommands
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "clouds" -d "Reconstruct 3D point clouds from depth"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "annotate" -d "Run ML inference on sensor frames"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "material" -d "Create blank material passport"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "project" -d "Project 2D labels onto 3D point cloud"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "planes" -d "Detect and segment planar surfaces"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "rooms" -d "Segment rooms using Leiden clustering"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "instances" -d "Separate labels into spatial instances"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "mesh" -d "Generate watertight mesh from planes"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "texture" -d "Apply textures to mesh from sensor frames"
complete -c rux -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from clouds annotate material project planes rooms instances mesh texture windows" -a "windows" -d "Create window building components"

# Options for: create
complete -c rux -n "__fish_seen_subcommand_from create" -s h -l help -d "Print this help message and exit"

# Options for: create clouds
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from clouds" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from clouds" -s g -l grid -d "Voxel grid resolution for downsampling" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from clouds" -l min-distance -d "Minimum depth in meters" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from clouds" -l max-distance -d "Maximum depth in meters" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from clouds" -l sampling-factor -d "Per-frame pixel subsampling factor" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from clouds" -l confidence -d "Minimum confidence threshold" -r

# Options for: create annotate
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from annotate" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from annotate" -s n -l net -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from annotate" -s c -l cuda -d "Use CUDA for YOLOv8 inference"

# Options for: create material
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from material" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from material" -l guid -d "Custom GUID for the material passport (default: auto-generated)" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from material" -s o -l output -d "Output JSON file path (optional)" -r

# Options for: create project
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s h -l help -d "Print this help message and exit"

# Options for: create planes
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -s a -l angle-threshold -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -s d -l plane-dist-threshold -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -s m -l min-cluster-size -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -s r -l radius -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -s i -l interval-0 -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -l interval-factor -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from planes" -s f -l filter -d "Filter expression to limit processing to specific labeled points." -r

# Options for: create rooms
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from rooms" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from rooms" -s r -l resolution -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from rooms" -s b -l beta -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from rooms" -s m -l max-iter -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from rooms" -s g -l grid-size -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from rooms" -s f -l filter -d "Filter expression to limit processing to specific labeled points." -r

# Options for: create instances
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from instances" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from instances" -s t -l tolerance -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from instances" -s m -l min-size -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from instances" -s M -l max-size -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from instances" -s s -l semantic -d "Input semantic labels cloud name" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from instances" -s o -l output -d "Output instance labels cloud name" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from instances" -s l -l labels -d "Comma-separated list of semantic labels to process (empty = all)" -r

# Options for: create mesh
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from mesh" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from mesh" -l output-name -d "Name for the output mesh in ProjectDB" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from mesh" -s a -l angle -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from mesh" -s l -l distance -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from mesh" -s t -l threshold -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from mesh" -s o -l offset -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from mesh" -s f -l filter -d "Filter expression to limit processing to specific labeled points." -r

# Options for: create texture
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from texture" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from texture" -s m -l mesh-name -d "Name of the input mesh in ProjectDB" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from texture" -s o -l output-name -r

# Options for: create windows
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -l mesh -d "Name of the wall mesh in ProjectDB" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -l instances -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -s s -l semantic -d "Name of semantic label cloud" -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -l mode -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -l offset -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -l alpha -r
complete -c rux -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from windows" -s l -l labels -d "Semantic labels to treat as windows (comma-separated)" -r

# import subcommands
complete -c rux -n "__fish_seen_subcommand_from import; and not __fish_seen_subcommand_from rtabmap materialepas" -a "rtabmap" -d "Import sensor data from RTABMap database"
complete -c rux -n "__fish_seen_subcommand_from import; and not __fish_seen_subcommand_from rtabmap materialepas" -a "materialepas" -d "Import material passports from JSON"

# Options for: import
complete -c rux -n "__fish_seen_subcommand_from import" -s h -l help -d "Print this help message and exit"

# Options for: import rtabmap
complete -c rux -n "__fish_seen_subcommand_from import; and __fish_seen_subcommand_from rtabmap" -s h -l help -d "Print this help message and exit"

# Options for: import materialepas
complete -c rux -n "__fish_seen_subcommand_from import; and __fish_seen_subcommand_from materialepas" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from import; and __fish_seen_subcommand_from materialepas" -l project-id -d "Project identifier (optional, passport stored without project if" -r

# export subcommands
complete -c rux -n "__fish_seen_subcommand_from export; and not __fish_seen_subcommand_from materialepas rhino speckle" -a "materialepas" -d "Export material passports to JSON"
complete -c rux -n "__fish_seen_subcommand_from export; and not __fish_seen_subcommand_from materialepas rhino speckle" -a "rhino" -d "Export labeled point cloud to Rhino 3DM"
complete -c rux -n "__fish_seen_subcommand_from export; and not __fish_seen_subcommand_from materialepas rhino speckle" -a "speckle" -d "Export point cloud or mesh to Speckle"

# Options for: export
complete -c rux -n "__fish_seen_subcommand_from export" -s h -l help -d "Print this help message and exit"

# Options for: export materialepas
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from materialepas" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from materialepas" -s o -l output -r

# Options for: export rhino
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from rhino" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from rhino" -s c -l cloud-name -d "Name of the point cloud in ProjectDB" -r
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from rhino" -s l -l labels-name -d "Name of the labels in ProjectDB (optional)" -r
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from rhino" -s o -l output -r

# Options for: export speckle
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -s d -l data-name -d "Name of the cloud or mesh in ProjectDB" -r
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -l mesh -d "Load as mesh instead of point cloud"
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -s s -l server -d "Speckle server URL (e.g., https://app.speckle.systems)" -r
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -s p -d "--project-id TEXT REQUIRED Project/stream ID (find in URL: /projects/{PROJECT_ID})"
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -s m -l model -d "Model/branch name (what users call 'model' in Speckle UI)" -r
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -s M -l message -r
complete -c rux -n "__fish_seen_subcommand_from export; and __fish_seen_subcommand_from speckle" -l max-batch -r

# Options for: get
complete -c rux -n "__fish_seen_subcommand_from get" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from get" -s o -l output -d "Write output to file instead of stdout" -r
complete -c rux -n "__fish_seen_subcommand_from get" -s p -l pretty -d "Pretty-print JSON output (default: auto-detect from TTY)"

# Options for: set
complete -c rux -n "__fish_seen_subcommand_from set" -s h -l help -d "Print this help message and exit"

# Options for: del
complete -c rux -n "__fish_seen_subcommand_from del" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from del" -s f -l force -d "Force deletion (required for wildcards, shows preview +"
complete -c rux -n "__fish_seen_subcommand_from del" -s y -l yes -d "Skip confirmation prompt (use with --force for scripts)"

# Options for: info
complete -c rux -n "__fish_seen_subcommand_from info" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from info" -s j -l json -d "Output in JSON format"

# Options for: log
complete -c rux -n "__fish_seen_subcommand_from log" -s h -l help -d "Print this help message and exit"
complete -c rux -n "__fish_seen_subcommand_from log" -s j -l json -d "Output in JSON format"
complete -c rux -n "__fish_seen_subcommand_from log" -s n -l limit -r

# Options for: view
complete -c rux -n "__fish_seen_subcommand_from view" -s h -l help -d "Print this help message and exit"
